GET http://localhost:3001/

###
GET http://localhost:3001/api/info

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/2
###
GET http://localhost:3001/api/persons/name/Arto%20Hellas

###
DELETE http://localhost:3001/api/persons/2
###
DELETE http://localhost:3001/api/persons/delete/2

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
 "id" : "f15c35ec-0931-44fb-9fa1-81bd4e2ec29f",   
 "name": "He",
 "number": "123-456-7890"
}
###
POST http://localhost:3001/api/persons/add
content-type: application/json

{
 "id" : "f15c35ec-0931-44fb-9fa1-81bd4e2ec29f",   
 "name": "October",
 "number": "123-4567890-"
}
###
PUT http://localhost:3001/api/persons/f162ddec-143d-4055-8adb-a334eb4c62b7
content-type: application/json

{
 "name": "Hello",
 "number": "13-456-7890"
}
###
PUT http://localhost:3001/api/persons/update/2
content-type: application/json

{
 "name": "Hello World 2",
 "number": "123-456-7890"
}
###
POST http://localhost:3001/api/persons/temp
content-type: application/json

{
"id": "2",
 "name": "Hello World 2",
 "number": "123-456-7890"
}