###
GET http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OWRiZGNhMDVhOWIzZWQ4NjBiYWMzMzkiLCJpYXQiOjE3NzYwOTEzNDgsImV4cCI6MTc3NjA5NDk0OH0.X-Q7QGrVRBACI0EuLloHYnKxruUTFlb2cpLVu-7EQz0

###
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OWRiZGNhMDVhOWIzZWQ4NjBiYWMzMzkiLCJpYXQiOjE3NzYwOTEzNDgsImV4cCI6MTc3NjA5NDk0OH0.X-Q7QGrVRBACI0EuLloHYnKxruUTFlb2cpLVu-7EQz0

{ 
 "title": "nma 2",
  "author": "nma",
  "url": "nma",
  "likes": 2
}
###
POST http://localhost:3001/api/blogs
content-type: application/json

{
 "title": "nma"
}
###
DELETE http://localhost:3001/api/blogs/69dbe2cd6a5b64329906c820
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OWRiZGNhMDVhOWIzZWQ4NjBiYWMzMzkiLCJpYXQiOjE3NzYwOTEzNDgsImV4cCI6MTc3NjA5NDk0OH0.X-Q7QGrVRBACI0EuLloHYnKxruUTFlb2cpLVu-7EQz0
###
PUT http://localhost:3001/api/blogs/69dbe2cd6a5b64329906c820
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OWRiZGNhMDVhOWIzZWQ4NjBiYWMzMzkiLCJpYXQiOjE3NzYwOTEzNDgsImV4cCI6MTc3NjA5NDk0OH0.X-Q7QGrVRBACI0EuLloHYnKxruUTFlb2cpLVu-7EQz0

{
 "title": "nma is nma but it is not",
  "author": "nma",
  "url": "nma",
  "likes": 4
}
###
GET http://localhost:3001/api/users
###
DELETE  http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
content-type: application/json

{
  "username": "mluukkai",
 "name": "Matti Luukkainen",
 "password": "salainen"
}
###

POST http://localhost:3001/api/login
content-type: application/json

{
 "username": "mluukkai",
 "password": "salainen"
}
###